// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/core/config"
	"github.com/gowvp/owl/internal/core/config/store/configdb"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

type ConfigAPI struct {
	configCore config.Core
	conf       *conf.Bootstrap
	uc         *Usecase
}

func NewConfigAPI(db *gorm.DB, conf *conf.Bootstrap) ConfigAPI {
	core := config.NewCore(configdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()))
	return ConfigAPI{configCore: core, conf: conf}
}

// configIDInput 配置 ID 路径参数
type configIDInput struct {
	ID int `uri:"id" binding:"required"`
}

// updateConfigInput 更新配置的请求参数（路径 ID + 请求体）
type updateConfigInput struct {
	ID int `uri:"id" binding:"required"`
	config.EditConfigInput
}

func registerConfig(g gin.IRouter, api ConfigAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/configs", handler...)
		// group.GET("", web.WrapH(api.listConfigs))
		// group.GET("/:id", web.WrapH(api.getConfig))
		// group.PUT("/:id", web.WrapH(api.updateConfig))
		// group.POST("", web.WrapH(api.createConfig))
		// group.DELETE("/:id", web.WrapH(api.deleteConfig))

		group.GET("/info", web.WrapH(api.getConfigInfo))
		group.PUT("/info/sip", web.WrapH(api.updateSIP))
	}
}

// >>> config >>>>>>>>>>>>>>>>>>>>

func (a ConfigAPI) listConfigs(c *gin.Context, in *config.FindConfigInput) (any, error) {
	items, total, err := a.configCore.ListConfigs(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ConfigAPI) getConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.GetConfig(c.Request.Context(), in.ID)
}

func (a ConfigAPI) updateConfig(c *gin.Context, in *updateConfigInput) (any, error) {
	return a.configCore.UpdateConfig(c.Request.Context(), &in.EditConfigInput, in.ID)
}

func (a ConfigAPI) createConfig(c *gin.Context, in *config.AddConfigInput) (any, error) {
	return a.configCore.CreateConfig(c.Request.Context(), in)
}

func (a ConfigAPI) deleteConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.DeleteConfig(c.Request.Context(), in.ID)
}

type getConfigInfoOutput struct {
	SIP conf.SIP `json:"sip"`
}

func (a ConfigAPI) getConfigInfo(c *gin.Context, _ *struct{}) (*getConfigInfoOutput, error) {
	return &getConfigInfoOutput{
		SIP: a.conf.Sip,
	}, nil
}

func (a ConfigAPI) updateSIP(_ *gin.Context, in *conf.SIP) (gin.H, error) {
	if err := copier.Copy(&a.conf.Sip, in); err != nil {
		return nil, reason.ErrServer.WithMsg(err.Error())
	}

	if err := conf.WriteConfig(a.conf, a.conf.ConfigPath); err != nil {
		return nil, reason.ErrServer.WithMsg(err.Error())
	}
	a.uc.SipServer.SetConfig()

	return gin.H{"msg": "ok"}, nil
}
