// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/gowvp/owl/internal/adapter/onvifadapter"
	"github.com/gowvp/owl/internal/core/bz"
	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/gowvp/owl/internal/core/recording"
	"github.com/gowvp/owl/internal/core/sms"
	"github.com/gowvp/owl/pkg/gbs"
	"github.com/gowvp/owl/pkg/zlm"
	"github.com/ixugo/goddd/pkg/hook"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
)

var ErrDevice = reason.NewError("ErrDevice", "设备错误")

const (
	coverDir = "cover"
)

// TODO: 快照不会删除，只会覆盖，设备删除时也不会删除快照，待实现
func writeCover(dataDir, channelID string, body []byte) error {
	coverPath := filepath.Join(dataDir, coverDir)
	if err := os.MkdirAll(coverPath, 0o777); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(coverPath, channelID+".jpg"), body, 0o644)
}

func readCoverPath(dataDir, channelID string) string {
	coverPath := filepath.Join(dataDir, coverDir)
	return filepath.Join(coverPath, channelID+".jpg")
}

func readCover(dataDir, channelID string) ([]byte, error) {
	return os.ReadFile(readCoverPath(dataDir, channelID))
}

type IPCAPI struct {
	ipc           ipc.Core
	uc            *Usecase
	recordingCore recording.Core
}

func NewIPCAPI(bundle IPCBundle, recordingCore recording.Core) IPCAPI {
	return IPCAPI{ipc: bundle.Core, recordingCore: recordingCore}
}

func registerGB28181(g gin.IRouter, api IPCAPI, handler ...gin.HandlerFunc) {
	// GB28181 协议特有的回调接口
	g.Any("/gb28181/snapshot", func(c *gin.Context) {
		b, err := io.ReadAll(c.Request.Body)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(orm.GenerateRandomString(10)+".jpg", b, 0o644); err != nil {
			slog.ErrorContext(c.Request.Context(), "write cover", "err", err)
		}
		c.JSON(200, gin.H{"msg": "ok"})
	})

	// 统一的设备管理 API（支持所有协议）
	{
		group := g.Group("/devices", handler...)
		group.GET("", web.WrapH(api.findDevice))                     // 设备列表（所有协议）
		group.GET("/:id", web.WrapH(api.getDevice))                  // 设备详情（所有协议）
		group.PUT("/:id", web.WrapH(api.editDevice))                 // 修改设备（所有协议）
		group.POST("", web.WrapH(api.addDevice))                     // 添加设备（所有协议，通过 type 区分）
		group.DELETE("/:id", web.WrapH(api.delDevice))               // 删除设备（所有协议）
		group.GET("/channels", web.WrapH(api.FindChannelsForDevice)) // 设备与通道列表（所有协议）
		group.POST("/:id/catalog", web.WrapH(api.queryCatalog))
	}
	{
		// group := g.Group("/onvif", handler...)
		g.GET("/onvif/discover", api.discover) // ONVIF 设备发现（ONVIF 特有）
		// group.GET("/discover", api.discover)   // ONVIF 设备发现（ONVIF 特有）
	}

	// 统一的通道管理 API（支持所有协议）
	{
		group := g.Group("/channels", handler...)
		group.GET("", web.WrapH(api.findChannel))                    // 通道列表（所有协议）
		group.POST("", web.WrapH(api.addChannel))                    // 添加通道（RTMP/RTSP）
		group.PUT("/:id", web.WrapH(api.editChannel))                // 修改通道（所有协议）
		group.DELETE("/:id", web.WrapH(api.delChannel))              // 删除通道（RTMP/RTSP）
		group.POST("/:id/play", web.WrapH(api.play))                 // 播放（所有协议）
		group.POST("/:id/snapshot", web.WrapH(api.refreshSnapshot))  // 图像抓拍（所有协议）
		group.GET("/:id/snapshot", api.getSnapshot)                  // 获取图像（所有协议）
		group.POST("/:id/zones", web.WrapH(api.addZone))             // 添加区域（所有协议）
		group.GET("/:id/zones", web.WrapH(api.getZones))             // 获取区域（所有协议）
		group.DELETE("/:id/zones/:name", web.WrapH(api.deleteZone))  // 删除区域（所有协议）
		group.POST("/:id/ai/enable", web.WrapH(api.enableAI))        // 启用 AI 检测
		group.POST("/:id/ai/disable", web.WrapH(api.disableAI))      // 禁用 AI 检测
		group.POST("/:id/record_mode", web.WrapH(api.setRecordMode)) // 设置录像模式
		group.POST("/:id/ptz/control", web.WrapH(api.ptzControl))    // 云台控制（所有协议）
		group.POST("/:id/stop", web.WrapH(api.stopPlay))             // 停止播放（所有协议）
	}
}

// >>> device >>>>>>>>>>>>>>>>>>>>

func (a IPCAPI) findDevice(c *gin.Context, in *ipc.FindDeviceInput) (any, error) {
	items, total, err := a.ipc.FindDevice(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a IPCAPI) getDevice(c *gin.Context, _ *struct{}) (any, error) {
	deviceID := c.Param("id")
	return a.ipc.GetDevice(c.Request.Context(), deviceID)
}

func (a IPCAPI) editDevice(c *gin.Context, in *ipc.EditDeviceInput) (any, error) {
	deviceID := c.Param("id")
	return a.ipc.EditDevice(c.Request.Context(), in, deviceID)
}

// addDevice 添加设备（支持所有协议类型）
// 通过 type 字段区分协议: "GB28181" 或 "ONVIF"
//
// 示例1 - 添加 GB28181 设备:
//
//	POST /devices
//	{ "type": "GB28181", "device_id": "34020000001320000001", "name": "摄像头1" }
//
// 示例2 - 添加 ONVIF 设备:
//
//	POST /devices
//	{ "type": "ONVIF", "ip": "192.168.1.100", "port": 80, "username": "admin", "password": "12345" }
func (a IPCAPI) addDevice(c *gin.Context, in *ipc.AddDeviceInput) (any, error) {
	in.Type = strings.ToUpper(in.Type)
	if !slices.Contains([]string{ipc.TypeGB28181, ipc.TypeOnvif}, in.Type) {
		return nil, reason.ErrBadRequest.SetMsg("不支持的设备类型")
	}
	return a.ipc.AddDevice(c.Request.Context(), in)
}

func (a IPCAPI) delDevice(c *gin.Context, _ *struct{}) (any, error) {
	did := c.Param("id")
	return a.ipc.DelDevice(c.Request.Context(), did)
}

func (a IPCAPI) queryCatalog(c *gin.Context, _ *struct{}) (any, error) {
	did := c.Param("id")

	if err := a.ipc.QueryCatalog(c.Request.Context(), did); err != nil {
		return nil, err
	}

	return gin.H{"msg": "ok"}, nil
}

func (a IPCAPI) FindChannelsForDevice(c *gin.Context, in *ipc.FindDeviceInput) (any, error) {
	ctx := c.Request.Context()
	items, total, err := a.ipc.FindChannelsForDevice(ctx, in)

	// 收集所有通道 ID 用于批量查询录像
	var cids []string
	for _, dev := range items {
		for _, ch := range dev.Children {
			cids = append(cids, ch.ID)
		}
	}

	// 批量查询哪些通道有录像
	hasRecordingMap, _ := a.recordingCore.HasRecordings(ctx, cids)

	// 为每个通道设置 has_recording 标记
	for _, dev := range items {
		for _, ch := range dev.Children {
			ch.HasRecording = hasRecordingMap[ch.ID]
		}
	}

	// 按照在线优先排序
	sort.SliceStable(items, func(i, j int) bool {
		return items[i].IsOnline && !items[j].IsOnline
	})
	// 按照第 1 个通道是否在线排序
	sort.SliceStable(items, func(i, j int) bool {
		if len(items[i].Children) > 0 && len(items[j].Children) > 0 {
			return items[i].Children[0].IsOnline && !items[j].Children[0].IsOnline
		}
		return false
	})

	return gin.H{"items": items, "total": total}, err
}

// >>> channel >>>>>>>>>>>>>>>>>>>>

func (a IPCAPI) findChannel(c *gin.Context, in *ipc.FindChannelInput) (any, error) {
	items, total, err := a.ipc.FindChannel(c.Request.Context(), in)
	if err != nil {
		return nil, err
	}

	// 为 RTMP 类型通道生成推流地址
	a.fillRTMPPushAddr(c, items)

	return gin.H{"items": items, "total": total}, nil
}

// fillRTMPPushAddr 为 RTMP 类型通道填充推流地址
func (a IPCAPI) fillRTMPPushAddr(c *gin.Context, items []*ipc.Channel) {
	if a.uc == nil {
		return
	}

	// 获取流媒体服务器配置
	ms, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), sms.DefaultMediaServerID)
	if err != nil {
		return
	}

	host := web.GetHost(c.Request)

	rtmpPort := ms.Ports.RTMP
	if rtmpPort == 0 {
		rtmpPort = 1935 // 默认 RTMP 端口
	}

	sign := hook.MD5(a.uc.Conf.Server.RTMPSecret)

	for _, item := range items {
		if item.IsRTMP() {
			item.Config.PushAddr = fmt.Sprintf("rtmp://%s:%d/%s/%s", host, rtmpPort, item.App, item.Stream)
			if !item.Config.IsAuthDisabled {
				item.Config.PushAddr += "?sign=" + sign
			}
		}
	}
}

// func (a GB28181API) getChannel(c *gin.Context, _ *struct{}) (any, error) {
// 	channelID := c.Param("id")
// 	return a.gb28181Core.GetChannel(c.Request.Context(), channelID)
// }

func (a IPCAPI) editChannel(c *gin.Context, in *ipc.EditChannelInput) (any, error) {
	cid := c.Param("id")
	ctx := c.Request.Context()

	old, err := a.ipc.GetChannel(ctx, cid)
	if err != nil {
		return nil, err
	}

	out, err := a.ipc.EditChannel(ctx, in, cid)
	if err != nil {
		return nil, err
	}

	// 流地址变更时，主动通知 ZLM 关闭旧的拉流
	if old.Config.SourceURL != "" && old.Config.SourceURL != out.Config.SourceURL {
		go a.closeOldStream(old)
	}

	return out, nil
}

// closeOldStream 流地址变更后关闭旧的 ZLM 拉流
func (a IPCAPI) closeOldStream(ch *ipc.Channel) {
	svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(context.Background(), sms.DefaultMediaServerID)
	if err != nil {
		slog.Warn("editChannel: 获取流媒体服务器失败", "err", err)
		return
	}
	resp, err := a.uc.SMSAPI.smsCore.CloseStreams(svr, zlm.CloseStreamsRequest{
		App:    ch.GetApp(),
		Stream: ch.GetStream(),
		Force:  true,
	})
	if err != nil {
		slog.Error("editChannel: 关闭旧流失败", "app", ch.GetApp(), "stream", ch.GetStream(), "err", err)
		return
	}
	slog.Info("editChannel: 旧流已关闭", "app", ch.GetApp(), "stream", ch.GetStream(), "closed", resp.CountClosed)
}

// addChannel 添加 RTMP/RTSP 通道
func (a IPCAPI) addChannel(c *gin.Context, in *ipc.AddChannelInput) (any, error) {
	in.Type = strings.ToUpper(in.Type)
	if !slices.Contains([]string{ipc.TypeRTMP, ipc.TypeRTSP}, in.Type) {
		return nil, reason.ErrBadRequest.SetMsg("仅支持 RTMP/RTSP 类型通道")
	}
	return a.ipc.AddChannel(c.Request.Context(), in)
}

// delChannel 删除 RTMP/RTSP 通道
func (a IPCAPI) delChannel(c *gin.Context, _ *struct{}) (any, error) {
	channelID := c.Param("id")

	// 仅允许删除 RTMP/RTSP 类型通道
	if !bz.IsRTMP(channelID) && !bz.IsRTSP(channelID) {
		return nil, reason.ErrBadRequest.SetMsg("仅支持删除 RTMP/RTSP 类型通道")
	}

	return a.ipc.DelChannel(c.Request.Context(), channelID)
}

func (a IPCAPI) play(c *gin.Context, _ *struct{}) (*playOutput, error) {
	channelID := c.Param("id")

	var app, appStream, host, stream, session, mediaServerID string

	// 国标逻辑
	if bz.IsGB28181(channelID) {
		// 防止错误的配置，无法收到流
		if a.uc.Conf.Media.SDPIP == "127.0.0.1" {
			return nil, reason.ErrUsedLogic.SetMsg("请先配置流媒体 SDP 收流地址")
		}
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}

		app = "rtp"
		appStream = ch.ID
		mediaServerID = sms.DefaultMediaServerID

	} else if bz.IsRTMP(channelID) {
		// 从 Channel 获取 RTMP 推流信息
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}
		if !ch.IsOnline {
			return nil, reason.ErrNotFound.SetMsg("未推流")
		}
		app = ch.App
		appStream = ch.Stream
		mediaServerID = ch.Config.MediaServerID
		if mediaServerID == "" {
			mediaServerID = sms.DefaultMediaServerID
		}

		if !ch.Config.IsAuthDisabled && ch.Config.Session != "" {
			session = "session=" + ch.Config.Session
		}
	} else if bz.IsRTSP(channelID) {
		// 从 Channel 获取 RTSP 拉流代理信息
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}
		app = ch.App
		if app == "" {
			app = "live"
		}
		appStream = ch.Stream
		mediaServerID = ch.Config.MediaServerID
		if mediaServerID == "" {
			mediaServerID = sms.DefaultMediaServerID
		}
	} else if bz.IsOnvif(channelID) {
		app = "live"
		appStream = channelID
		mediaServerID = sms.DefaultMediaServerID
	} else {
		return nil, reason.ErrNotFound.SetMsg("不支持的播放通道")
	}

	if !a.uc.SMSAPI.smsCore.IsOnline(mediaServerID) {
		return nil, reason.ErrNotFound.SetMsg("Oops! 流媒体服务离线或IP有误")
	}
	svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), mediaServerID)
	if err != nil {
		return nil, err
	}

	stream = app + "/" + appStream

	host = c.Request.Host
	if l := strings.Split(c.Request.Host, ":"); len(l) == 2 {
		host = l[0]
	}
	httpPort := a.uc.Conf.Server.HTTP.Port

	// 播放规则
	// https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99
	prefix := c.Request.Header.Get("X-Forwarded-Prefix")
	if prefix == "" {
		prefix = "http://" + host + ":" + strconv.Itoa(httpPort)
	}
	if h := c.Request.Header.Get("X-Forwarded-Host"); h != "" {
		host = h
	}

	item := a.uc.SMSAPI.smsCore.GetStreamLiveAddr(svr, prefix, host, app, appStream)
	out := playOutput{
		App:    app,
		Stream: appStream,
		Items:  []sms.StreamLiveAddr{item},
	}

	// 取一张快照
	go func() {
		rtsp := fmt.Sprintf("rtsp://%s:%d/%s", "127.0.0.1", svr.Ports.RTSP, stream) + "?" + session
		for range 2 {
			time.Sleep(3 * time.Second)

			body, err := a.uc.SMSAPI.smsCore.GetSnapshot(svr, sms.GetSnapRequest{
				GetSnapRequest: zlm.GetSnapRequest{
					URL:        rtsp,
					TimeoutSec: 10,
					ExpireSec:  15,
				},
				Stream: channelID,
			})
			if err != nil {
				slog.ErrorContext(c.Request.Context(), "get snapshot", "err", err)
				continue
			}
			if err := writeCover(a.uc.Conf.ConfigDir, channelID, body); err != nil {
				slog.ErrorContext(c.Request.Context(), "write cover", "err", err)
			}
			break
		}
		// if a.uc.Conf.Server.AI.Disabled || a.uc.AIWebhookAPI.ai == nil {
		// 	return
		// }

		// if _, ok := a.uc.AIWebhookAPI.aiTasks.LoadOrStore(channelID, struct{}{}); !ok {
		// 	resp, err := a.uc.AIWebhookAPI.ai.StartCamera(context.Background(), &protos.StartCameraRequest{
		// 		CameraId:       appStream,
		// 		CameraName:     appStream,
		// 		RtspUrl:        rtsp,
		// 		DetectFps:      5,
		// 		Labels:         []string{"person", "car", "cat", "dog"},
		// 		Threshold:      0.65,
		// 		RetryLimit:     10,
		// 		CallbackUrl:    fmt.Sprintf("http://127.0.0.1:%d/ai", a.uc.Conf.Server.HTTP.Port),
		// 		CallbackSecret: "Basic 1234567890",
		// 	})
		// 	if err != nil {
		// 		slog.Error("start camera", "err", err)
		// 		return
		// 	}
		// 	slog.Debug("start camera", "resp", resp,
		// 		"msg", resp.GetMessage(),
		// 		"source_width", resp.GetSourceWidth(),
		// 		"source_height", resp.GetSourceHeight(),
		// 		"source_fps", resp.GetSourceFps(),
		// 	)
		// }
	}()
	return &out, nil
}

// stopPlay 停止播放（幂等：始终返回成功）
//
// 根据通道协议类型分发：
//   - GB28181: SIP BYE + CloseRTPServer
//   - ONVIF/RTSP/RTMP: ZLM close_streams
func (a IPCAPI) stopPlay(c *gin.Context, _ *struct{}) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()
	log := slog.With("channel_id", channelID)

	ch, err := a.ipc.GetChannel(ctx, channelID)
	if err != nil {
		return nil, reason.ErrBadRequest.SetMsg("通道不存在")
	}

	log = log.With("type", ch.GetType())

	if bz.IsGB28181(channelID) {
		device, err := a.ipc.GetDevice(ctx, ch.DID)
		if err != nil {
			return nil, reason.ErrBadRequest.SetMsg("设备不存在")
		}

		protocol := a.ipc.GetProtocol(ch.GetType())
		if protocol == nil {
			return nil, reason.ErrBadRequest.SetMsg("协议适配器不存在")
		}

		if err := protocol.StopPlay(ctx, device, ch); err != nil {
			log.ErrorContext(ctx, "停止播放：GB28181 StopPlay 失败", "err", err)
		}

		// 关闭 ZLM 的 RTP 接收端口
		svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(ctx, sms.DefaultMediaServerID)
		if err == nil {
			if _, err := a.uc.SMSAPI.smsCore.CloseRTPServer(svr, zlm.CloseRTPServerRequest{
				StreamID: ch.GetStream(),
			}); err != nil {
				log.WarnContext(ctx, "停止播放：CloseRTPServer 失败", "err", err)
			}
		}
	} else {
		// ONVIF/RTSP/RTMP 统一通过 ZLM close_streams 关闭
		svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(ctx, sms.DefaultMediaServerID)
		if err != nil {
			log.WarnContext(ctx, "停止播放：获取流媒体服务器失败", "err", err)
			return gin.H{"msg": "ok"}, nil
		}

		app := ch.GetApp()
		stream := ch.GetStream()
		log.InfoContext(ctx, "停止播放：关闭流", "app", app, "stream", stream)

		resp, err := a.uc.SMSAPI.smsCore.CloseStreams(svr, zlm.CloseStreamsRequest{
			App:    app,
			Stream: stream,
			Force:  true,
		})
		if err != nil {
			log.ErrorContext(ctx, "停止播放：CloseStreams 失败", "err", err)
		} else {
			log.InfoContext(ctx, "停止播放：CloseStreams 完成", "count_hit", resp.CountHit, "count_closed", resp.CountClosed)
		}

		// 更新播放状态
		if _, err := a.ipc.EditChannelPlaying(ctx, ch.GetStream(), false); err != nil {
			log.WarnContext(ctx, "停止播放：更新播放状态失败", "err", err)
		}
	}

	log.InfoContext(ctx, "停止播放完成")
	return gin.H{"msg": "ok"}, nil
}

type refreshSnapshotInput struct {
	// 指定获取多少秒内创建的快照
	WithinSeconds int64 `json:"within_seconds"`
	// 取快照的链接地址
	URL string `json:"url"`
}

func (a IPCAPI) refreshSnapshot(c *gin.Context, in *refreshSnapshotInput) (any, error) {
	channelID := c.Param("id")

	path := readCoverPath(a.uc.Conf.ConfigDir, channelID)

	token := c.GetString("token")

	prefix := web.GetBaseURL(c.Request)
	if v := c.Request.Header.Get("X-Forwarded-Prefix"); v != "" {
		prefix = v
	}

	// 获取文件的修改时间
	fileInfo, err := os.Stat(path)
	if err == nil {
		if fileInfo.ModTime().Unix() > time.Now().Unix()-in.WithinSeconds {
			return gin.H{"link": fmt.Sprintf("%s/channels/%s/snapshot?token=%s", prefix, channelID, token)}, nil
		}
	}

	if in.URL != "" {
		svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), sms.DefaultMediaServerID)
		if err != nil {
			return nil, err
		}

		img, err := a.uc.SMSAPI.smsCore.GetSnapshot(svr, sms.GetSnapRequest{
			GetSnapRequest: zlm.GetSnapRequest{
				URL:        in.URL,
				TimeoutSec: 10,
				ExpireSec:  int(in.WithinSeconds),
			},
			Stream: channelID,
		})
		if err != nil {
			slog.ErrorContext(c.Request.Context(), "get snapshot", "err", err)
			// return nil, reason.ErrBadRequest.Msg(err.Error())
		} else {
			if hook.MD5FromBytes(img) != "" {
				if err := writeCover(a.uc.Conf.ConfigDir, channelID, img); err != nil {
					slog.ErrorContext(c.Request.Context(), "write cover", "err", err)
				}
			}
		}
	}

	return gin.H{"link": fmt.Sprintf("%s/channels/%s/snapshot?token=%s", prefix, channelID, token)}, nil
}

func (a IPCAPI) addZone(c *gin.Context, in *ipc.AddZoneInput) (gin.H, error) {
	ctx := c.Request.Context()
	channelID := c.Param("id")
	if len(in.Labels) == 0 {
		in.Labels = []string{"person", "car", "cat", "dog"}
	}
	zones, err := a.ipc.AddZone(ctx, in, channelID)
	if err != nil {
		return nil, err
	}

	// 区域写入后，若 AI 已开启则立即重启任务使新区域生效
	if a.uc != nil {
		ch, chErr := a.ipc.GetChannel(ctx, channelID)
		if chErr == nil && ch.Ext.EnabledAI {
			if reloadErr := a.uc.AIWebhookAPI.ReloadAITask(ctx, ch); reloadErr != nil {
				slog.WarnContext(ctx, "reload AI task after zone update failed", "camera_id", channelID, "err", reloadErr)
			}
		}
	}
	return gin.H{"items": zones}, nil
}

func (a IPCAPI) getZones(c *gin.Context, _ *struct{}) (any, error) {
	channelID := c.Param("id")
	return a.ipc.GetZones(c.Request.Context(), channelID)
}

func (a IPCAPI) deleteZone(c *gin.Context, _ *struct{}) (gin.H, error) {
	ctx := c.Request.Context()
	channelID := c.Param("id")
	zoneName := c.Param("name")

	zones, err := a.ipc.DeleteZone(ctx, channelID, zoneName)
	if err != nil {
		return nil, err
	}

	// 删除区域后，若 AI 已开启则立即重启任务使变更生效
	if a.uc != nil {
		ch, chErr := a.ipc.GetChannel(ctx, channelID)
		if chErr == nil && ch.Ext.EnabledAI {
			if reloadErr := a.uc.AIWebhookAPI.ReloadAITask(ctx, ch); reloadErr != nil {
				slog.WarnContext(ctx, "reload AI task after zone delete failed", "camera_id", channelID, "err", reloadErr)
			}
		}
	}
	return gin.H{"items": zones}, nil
}

func (a IPCAPI) getSnapshot(c *gin.Context) {
	channelID := c.Param("id")
	body, err := readCover(a.uc.Conf.ConfigDir, channelID)
	if err != nil {
		web.Fail(c, reason.ErrNotFound.SetMsg(err.Error()))
		return
	}
	c.Data(200, "image/jpeg", body)
}

func (a IPCAPI) discover(c *gin.Context) {
	p := a.ipc.GetProtocol(ipc.TypeOnvif)
	onvifAdapter, ok := p.(*onvifadapter.Adapter)
	if !ok {
		web.Fail(c, reason.ErrNotFound.SetMsg("不支持的协议"))
		return
	}

	se := web.NewSSE(64, time.Minute)
	go func() {
		defer func() {
			se.Publish(web.Event{
				ID:    uuid.NewString(),
				Event: "end",
			})
			se.Close()
		}()
		w := IOWriter{fn: func(b []byte) (int, error) {
			se.Publish(web.Event{
				ID:    uuid.NewString(),
				Event: "discover",
				Data:  b,
			})
			return len(b), nil
		}}
		if err := onvifAdapter.Discover(c.Request.Context(), w); err != nil {
			slog.ErrorContext(c.Request.Context(), "discover", "err", err)
		}
	}()
	se.ServeHTTP(c.Writer, c.Request)
}

type IOWriter struct {
	fn func(b []byte) (int, error)
}

func (w IOWriter) Write(b []byte) (int, error) {
	return w.fn(b)
}

var (
	ErrAIGlobalDisabled    = reason.NewError("ErrAIGlobalDisabled", "AI 功能已在全局配置中禁用")
	ErrAIServiceNotReady   = reason.NewError("ErrAIServiceNotReady", "AI 服务未初始化或连接失败")
	ErrChannelNotSupported = reason.NewError("ErrChannelNotSupported", "不支持的通道类型")
)

// enableAI 启用指定通道的 AI 检测功能，需要先确保全局 AI 服务已启用且连接正常
func (a IPCAPI) enableAI(c *gin.Context, _ *struct{}) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 检查全局 AI 配置
	if a.uc.Conf.Server.AI.Disabled {
		return nil, ErrAIGlobalDisabled
	}
	if a.uc.AIWebhookAPI.ai == nil {
		return nil, ErrAIServiceNotReady
	}

	// 更新数据库中的 AI 启用状态
	channel, err := a.ipc.SetAIEnabled(ctx, channelID, true)
	if err != nil {
		return nil, err
	}

	// 构建 RTSP 地址
	rtspURL, err := a.buildRTSPURL(ctx, channelID)
	if err != nil {
		return nil, err
	}

	// 启动 AI 检测任务
	resp, err := a.uc.AIWebhookAPI.StartAIDetection(ctx, channel, rtspURL)
	if err != nil {
		slog.ErrorContext(ctx, "start camera AI", "err", err)
		return nil, reason.ErrUsedLogic.SetMsg("启动 AI 检测失败: " + err.Error())
	}

	return gin.H{
		"enabled":       true,
		"message":       resp.GetMessage(),
		"source_width":  resp.GetSourceWidth(),
		"source_height": resp.GetSourceHeight(),
		"source_fps":    resp.GetSourceFps(),
	}, nil
}

// disableAI 禁用指定通道的 AI 检测功能，会同时停止正在运行的检测任务
func (a IPCAPI) disableAI(c *gin.Context, _ *struct{}) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 检查全局 AI 配置
	if a.uc.Conf.Server.AI.Disabled {
		return nil, ErrAIGlobalDisabled
	}
	if a.uc.AIWebhookAPI.ai == nil {
		return nil, ErrAIServiceNotReady
	}

	// 更新数据库中的 AI 启用状态
	if _, err := a.ipc.SetAIEnabled(ctx, channelID, false); err != nil {
		return nil, err
	}

	// 停止 AI 检测任务
	if err := a.uc.AIWebhookAPI.StopAIDetection(ctx, channelID); err != nil {
		slog.ErrorContext(ctx, "stop camera AI", "err", err)
	}

	return gin.H{
		"enabled": false,
		"message": "AI 检测已停止",
	}, nil
}

// buildRTSPURL 根据通道类型构建对应的 RTSP 播放地址
func (a IPCAPI) buildRTSPURL(ctx context.Context, channelID string) (string, error) {
	svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(ctx, sms.DefaultMediaServerID)
	if err != nil {
		return "", err
	}

	var app, stream string

	if bz.IsGB28181(channelID) {
		app = "rtp"
		stream = channelID
	} else if bz.IsOnvif(channelID) {
		app = "live"
		stream = channelID
	} else if bz.IsRTSP(channelID) || bz.IsRTMP(channelID) {
		// 从 Channel 获取流信息
		ch, err := a.ipc.GetChannel(ctx, channelID)
		if err != nil {
			return "", err
		}
		app = ch.App
		if app == "" {
			app = "live"
		}
		stream = ch.Stream
	} else {
		return "", ErrChannelNotSupported
	}

	return fmt.Sprintf("rtsp://%s:%d/%s/%s", "127.0.0.1", svr.Ports.RTSP, app, stream), nil
}

// setRecordModeInput 设置录像模式请求参数
type setRecordModeInput struct {
	// 录像模式：always-一直录制，ai-按AI触发录制，none-不录制
	Mode string `json:"mode" binding:"required,oneof=always ai none"`
}

// setRecordMode 设置通道的录像模式，支持三种模式：always(一直录制)、ai(AI触发录制)、none(不录制)
// always 和 ai 都会启用录制
func (a IPCAPI) setRecordMode(c *gin.Context, in *setRecordModeInput) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 更新通道的录像模式
	channel, err := a.ipc.SetRecordMode(ctx, channelID, in.Mode)
	if err != nil {
		return nil, err
	}

	// 根据录像模式控制 ZLM 录制：
	// - always/ai: 如果流在线则启动录制
	// - none: 停止录制
	if channel.Ext.IsNoneRecord() {
		// none 模式：停止录制
		if err := a.recordingCore.StopRecording(ctx, channel.GetApp(), channel.GetStream()); err != nil {
			slog.WarnContext(ctx, "停止录制失败", "channel", channelID, "err", err)
		}
	} else {
		// always/ai 模式：如果流在线则启动录制
		if channel.IsOnline {
			if err := a.recordingCore.StartRecording(ctx, channel.GetType(), channel.GetApp(), channel.GetStream()); err != nil {
				slog.WarnContext(ctx, "启动录制失败", "channel", channelID, "err", err)
			}
		}
	}

	return gin.H{
		"id":          channel.ID,
		"record_mode": channel.Ext.GetRecordMode(),
	}, nil
}

// ptzControlInput PTZ 控制请求参数
type ptzControlInput struct {
	Action    string  `json:"action" binding:"required,oneof=continuous stop absolute relative preset"` // 动作类型
	Direction string  `json:"direction"`                                                                // 方向（连续移动时使用）
	Speed     float64 `json:"speed"`                                                                    // 速度 (0-1)
	X         float64 `json:"x"`                                                                        // X 轴位置
	Y         float64 `json:"y"`                                                                        // Y 轴位置
	Zoom      float64 `json:"zoom"`                                                                     // 缩放值
	PresetID  string  `json:"preset_id"`                                                                // 预置位 ID
	PresetOp  string  `json:"preset_op" binding:"omitempty,oneof=goto set remove"`                      // 预置位操作
}

// ptzControl 云台控制接口
func (a IPCAPI) ptzControl(c *gin.Context, in *ptzControlInput) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 获取通道信息
	channel, err := a.ipc.GetChannel(ctx, channelID)
	if err != nil {
		return nil, err
	}

	// 获取设备信息
	device, err := a.ipc.GetDevice(ctx, channel.DID)
	if err != nil {
		return nil, err
	}

	// 检查设备是否在线
	if !device.IsOnline {
		return nil, reason.ErrBadRequest.SetMsg("设备离线")
	}

	slog.InfoContext(ctx, "PTZ 控制请求（跳过协议判断）",
		"channel_id", channelID,
		"channel_device_id", channel.DeviceID,
		"channel_channel_id", channel.ChannelID,
		"channel_ptztype", channel.PTZ, // 添加 PTZ 类型
		"device_id", device.ID,
		"device_type", device.GetType(),
		"action", in.Action,
		"direction", in.Direction)

	// 直接使用 GB28181 的 PTZ 控制逻辑发送指令
	var ptzCmd string
	switch in.Action {
	case "continuous":
		// 连续移动
		ptzCmd = gbs.BuildContinuousMove(in.Direction, in.Speed)
		if ptzCmd == "" {
			return nil, fmt.Errorf("不支持的方向: %s", in.Direction)
		}
		slog.InfoContext(ctx, "构建连续移动命令",
			"direction", in.Direction,
			"speed", in.Speed,
			"ptz_cmd", ptzCmd)
	case "stop":
		// 停止移动
		ptzCmd = gbs.BuildStop()
		slog.InfoContext(ctx, "构建停止命令", "ptz_cmd", ptzCmd)
	default:
		return nil, fmt.Errorf("暂不支持的动作类型: %s，仅支持 continuous 和 stop", in.Action)
	}

	// 直接调用 GB28181 Server 发送 PTZ 命令
	// 使用通道的 DeviceID（国标编码）和 ChannelID 作为目标
	if err := a.uc.SipServer.PTZControl(device.DeviceID, channel.ChannelID, ptzCmd); err != nil {
		slog.ErrorContext(ctx, "PTZ 控制失败", "err", err)
		return nil, err
	}

	slog.InfoContext(ctx, "PTZ 控制指令已发送", "ptz_cmd", ptzCmd)

	return gin.H{
		"msg": "PTZ 控制指令已发送",
	}, nil
}
