// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/core/sms"
	"github.com/gowvp/owl/internal/core/sms/store/smsdb"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"gorm.io/gorm"
)

type SmsAPI struct {
	smsCore sms.Core
	uc      *Usecase
}

func NewSMSCore(db *gorm.DB, cfg *conf.Bootstrap) sms.Core {
	core := sms.NewCore(smsdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()))
	if err := core.Run(cfg, cfg.Server.HTTP.Port); err != nil {
		panic(err)
	}
	return core
}

func NewSmsAPI(core sms.Core) SmsAPI {
	return SmsAPI{smsCore: core}
}

// mediaServerIDInput 流媒体服务器 ID 路径参数
type mediaServerIDInput struct {
	ID string `uri:"id" binding:"required"`
}

// updateMediaServerInput 更新流媒体服务器的请求参数（路径 ID + 请求体）
type updateMediaServerInput struct {
	ID string `uri:"id" binding:"required"`
	sms.EditMediaServerInput
}

func registerSms(g gin.IRouter, api SmsAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/media_servers", handler...)
		group.GET("", web.WrapH(api.listMediaServers))
		group.PUT("/:id", web.WrapH(api.updateMediaServer))

		// group.GET("/:id", web.WrapH(api.getMediaServer))
		// group.POST("", web.WrapH(api.createMediaServer))
		// group.DELETE("/:id", web.WrapH(api.deleteMediaServer))
	}
}

// >>> mediaServer >>>>>>>>>>>>>>>>>>>>

func (a SmsAPI) listMediaServers(c *gin.Context, in *sms.FindMediaServerInput) (any, error) {
	items, total, err := a.smsCore.ListMediaServers(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a SmsAPI) getMediaServer(c *gin.Context, in *mediaServerIDInput) (any, error) {
	return a.smsCore.GetMediaServer(c.Request.Context(), in.ID)
}

func (a SmsAPI) updateMediaServer(c *gin.Context, in *updateMediaServerInput) (any, error) {
	out, err := a.smsCore.UpdateMediaServer(c.Request.Context(), &in.EditMediaServerInput, in.ID, a.uc.Conf.Server.HTTP.Port)
	if err != nil {
		return nil, err
	}
	if in.ID == "local" {
		a.uc.Conf.Media.IP = out.IP
		a.uc.Conf.Media.SDPIP = out.SDPIP
		a.uc.Conf.Media.Secret = out.Secret
		a.uc.Conf.Media.WebHookIP = out.HookIP
		a.uc.Conf.Media.Type = out.Type
		if err := conf.WriteConfig(a.uc.Conf, a.uc.Conf.ConfigPath); err != nil {
			return nil, reason.ErrServer.WithMsg(err.Error())
		}
	}
	return out, err
}

func (a SmsAPI) createMediaServer(c *gin.Context, in *sms.AddMediaServerInput) (any, error) {
	return a.smsCore.CreateMediaServer(c.Request.Context(), in)
}

func (a SmsAPI) deleteMediaServer(c *gin.Context, in *mediaServerIDInput) (any, error) {
	return a.smsCore.DeleteMediaServer(c.Request.Context(), in.ID)
}
