// Code generated by godddx, DO AVOID EDIT.
package proxy

import (
	"context"
	"log/slog"

	"github.com/gowvp/owl/internal/core/bz"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// StreamProxyStorer Instantiation interface
type StreamProxyStorer interface {
	List(context.Context, *[]*StreamProxy, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *StreamProxy, ...orm.QueryOption) error
	Create(context.Context, *StreamProxy) error
	Update(context.Context, *StreamProxy, func(*StreamProxy), ...orm.QueryOption) error
	Delete(context.Context, *StreamProxy, ...orm.QueryOption) error
}

// ListStreamProxys Paginated search
func (c *Core) ListStreamProxys(ctx context.Context, in *FindStreamProxyInput) ([]*StreamProxy, int64, error) {
	query := orm.NewQuery(1)
	query.OrderBy("created_at desc")

	items := make([]*StreamProxy, 0)
	total, err := c.store.StreamProxy().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}
	return items, total, nil
}

// GetStreamProxy Query a single object
func (c *Core) GetStreamProxy(ctx context.Context, id string) (*StreamProxy, error) {
	var out StreamProxy
	if err := c.store.StreamProxy().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

func (c *Core) GetStreamProxyByAppStream(ctx context.Context, app, stream string) (*StreamProxy, error) {
	var out StreamProxy
	if err := c.store.StreamProxy().Get(ctx, &out, orm.Where("app=? AND stream=?", app, stream)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// CreateStreamProxy Insert into database
func (c *Core) CreateStreamProxy(ctx context.Context, in *AddStreamProxyInput) (*StreamProxy, error) {
	var out StreamProxy
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	out.ID = c.uniqueID.UniqueID(bz.IDPrefixRTSP)
	out.Stream = out.ID
	out.App = "live"
	if err := c.store.StreamProxy().Create(ctx, &out); err != nil {
		if orm.IsDuplicatedKey(err) {
			return nil, reason.ErrDB.WithMsg("stream 重复，请勿重复添加")
		}
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateStreamProxy Update object information
func (c *Core) UpdateStreamProxy(ctx context.Context, in *EditStreamProxyInput, id string) (*StreamProxy, error) {
	var out StreamProxy
	if err := c.store.StreamProxy().Update(ctx, &out, func(b *StreamProxy) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	return &out, nil
}

func (c *Core) UpdateStreamProxyKey(ctx context.Context, streamKey, id string) (*StreamProxy, error) {
	var out StreamProxy
	if err := c.store.StreamProxy().Update(ctx, &out, func(b *StreamProxy) {
		out.StreamKey = streamKey
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	return &out, nil
}

// DeleteStreamProxy Delete object
func (c *Core) DeleteStreamProxy(ctx context.Context, id string) (*StreamProxy, error) {
	var out StreamProxy
	if err := c.store.StreamProxy().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}
	return &out, nil
}
